version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.75
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafkaui:
    image: provectuslabs/kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
  
  api:
    image: opa_api
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - zookeeper
      - kafkaui
    environment:
      KAFKA_HOST: 192.168.1.75
      API_DEBUG: 1
  
  app:
    image: opa_app
    ports:
      - "8050:8050"
    environment:
        API_HOST: 'http://api:5000'
    depends_on:
      - kafka
      - zookeeper
      - kafkaui
      - api